# Book settings
title:
author: World Bank Development Data Group
copyright: "2023"
logo: docs/images/logo.png
only_build_toc_files: true

repository:
    url: https://github.com/datapartnership/turkiye-earthquake-impact
    branch: main

html:
    home_page_in_navbar: false
    extra_navbar: ""
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    baseurl: https://datapartnership.github.io/turkiye-earthquake-impact

# Execution settings
execute:
    execute_notebooks: force
    allow_errors: true
    exclude_patterns:
        - notebooks/*.ipynb

sphinx:
    config:
        html_show_copyright: false
        html_last_updated_fmt: "%b %d, %Y"
