# Book settings
title:
author: World Bank Development Data Group
copyright: 2023
logo: docs/images/logo.png

repository:
    url: https://github.com/datapartnership/turkiye-rapid-damage-and-needs-assessment
    branch: main

html:
    home_page_in_navbar: false
    extra_navbar: ""
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    baseurl: https://datapartnership.github.io/turkiye-rapid-damage-and-needs-assessment

only_build_toc_files: true
